# experiment
model: bayesian_svdpp # regularized_svd, svdpp, bayesian_svdpp
experiment_name: 28may_bayessvdpp_batch256_emb30
mode: 'both' # train or evaluate or both

# directory info
data_path: ../data/ratings.dat
log_dir: ../logs
checkpoint_dir: ../checkpoints

# train test split
test_size: 0.1
valid_size: 0.1
test_split_random_state: 42
valid_split_random_state: 0

# training
num_users: 6040  #movielens 1m
num_items: 3952  #movielens 1m
epochs: 100
batch_size: 256
learning_rate: 0.001
embedding_dim: 30
beta: 0.00003  # weight decay coef
kl_coef: 0.000001  # only relevant for bayesian_svdpp







